
/**
* LibraryInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LibraryInterface.idl
* Wednesday, November 5, 2014 2:29:08 o'clock AM EST
*/

public interface LibraryInterfaceOperations 
{
  String createAccount (String firstName, String lastName, String email, String phoneNumber, String username, String password, String educationalInstitute);
  String reserveBook (String username, String password, String bookName, String authorName);
  String reserveInterLibrary (String username, String password, String bookName, String authorName);
  String[] getNonReturners (String username, String password, String educationalInstitute, int days);
  boolean setDuration (String username, String password, String studentUsername, String bookName, String authorName, int days);
} // interface LibraryInterfaceOperations
