
/**
* LibraryInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LibraryInterface.idl
* Wednesday, November 5, 2014 2:29:08 o'clock AM EST
*/

public abstract class LibraryInterfacePOA extends org.omg.PortableServer.Servant
 implements LibraryInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("createAccount", new java.lang.Integer (0));
    _methods.put ("reserveBook", new java.lang.Integer (1));
    _methods.put ("reserveInterLibrary", new java.lang.Integer (2));
    _methods.put ("getNonReturners", new java.lang.Integer (3));
    _methods.put ("setDuration", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // LibraryInterface/createAccount
       {
         String firstName = in.read_string ();
         String lastName = in.read_string ();
         String email = in.read_string ();
         String phoneNumber = in.read_string ();
         String username = in.read_string ();
         String password = in.read_string ();
         String educationalInstitute = in.read_string ();
         String $result = null;
         $result = this.createAccount (firstName, lastName, email, phoneNumber, username, password, educationalInstitute);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // LibraryInterface/reserveBook
       {
         String username = in.read_string ();
         String password = in.read_string ();
         String bookName = in.read_string ();
         String authorName = in.read_string ();
         String $result = null;
         $result = this.reserveBook (username, password, bookName, authorName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // LibraryInterface/reserveInterLibrary
       {
         String username = in.read_string ();
         String password = in.read_string ();
         String bookName = in.read_string ();
         String authorName = in.read_string ();
         String $result = null;
         $result = this.reserveInterLibrary (username, password, bookName, authorName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // LibraryInterface/getNonReturners
       {
         String username = in.read_string ();
         String password = in.read_string ();
         String educationalInstitute = in.read_string ();
         int days = in.read_long ();
         String $result[] = null;
         $result = this.getNonReturners (username, password, educationalInstitute, days);
         out = $rh.createReply();
         LibraryInterfacePackage.resultHelper.write (out, $result);
         break;
       }

       case 4:  // LibraryInterface/setDuration
       {
         String username = in.read_string ();
         String password = in.read_string ();
         String studentUsername = in.read_string ();
         String bookName = in.read_string ();
         String authorName = in.read_string ();
         int days = in.read_long ();
         boolean $result = false;
         $result = this.setDuration (username, password, studentUsername, bookName, authorName, days);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:LibraryInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public LibraryInterface _this() 
  {
    return LibraryInterfaceHelper.narrow(
    super._this_object());
  }

  public LibraryInterface _this(org.omg.CORBA.ORB orb) 
  {
    return LibraryInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class LibraryInterfacePOA
