
/**
* LibraryInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LibraryInterface.idl
* Wednesday, November 5, 2014 2:29:08 o'clock AM EST
*/

public final class LibraryInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public LibraryInterface value = null;

  public LibraryInterfaceHolder ()
  {
  }

  public LibraryInterfaceHolder (LibraryInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = LibraryInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    LibraryInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return LibraryInterfaceHelper.type ();
  }

}
