
/**
* LibraryInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LibraryInterface.idl
* Wednesday, November 5, 2014 2:29:08 o'clock AM EST
*/

public interface LibraryInterface extends LibraryInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface LibraryInterface
