package idl;


/**
* idl/_ReplicaManagerStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/ReplicaManager.idl
* Wednesday, November 26, 2014 10:37:55 PM EST
*/

public class _ReplicaManagerStub extends org.omg.CORBA.portable.ObjectImpl implements idl.ReplicaManager
{

  public void handleFailure (String educationalInstitution, String rmId)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("handleFailure", true);
                $out.write_string (educationalInstitution);
                $out.write_string (rmId);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                handleFailure (educationalInstitution, rmId        );
            } finally {
                _releaseReply ($in);
            }
  } // handleFailure

  public void sendHeartBeats ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("sendHeartBeats", true);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                sendHeartBeats (        );
            } finally {
                _releaseReply ($in);
            }
  } // sendHeartBeats

  public String processHeartBeat (String educationalInstitution)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("processHeartBeat", true);
                $out.write_string (educationalInstitution);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return processHeartBeat (educationalInstitution        );
            } finally {
                _releaseReply ($in);
            }
  } // processHeartBeat

  public boolean getCrashAgreement (int crashedRMId, int notifierRMId)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getCrashAgreement", true);
                $out.write_long (crashedRMId);
                $out.write_long (notifierRMId);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getCrashAgreement (crashedRMId, notifierRMId        );
            } finally {
                _releaseReply ($in);
            }
  } // getCrashAgreement

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:idl/ReplicaManager:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _ReplicaManagerStub
