package idl;


/**
* idl/LibraryPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/ReplicaManager.idl
* Wednesday, November 26, 2014 10:37:55 PM EST
*/

public abstract class LibraryPOA extends org.omg.PortableServer.Servant
 implements idl.LibraryOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("createAccount", new java.lang.Integer (0));
    _methods.put ("reserveBook", new java.lang.Integer (1));
    _methods.put ("reserveInterLibrary", new java.lang.Integer (2));
    _methods.put ("getNonRetuners", new java.lang.Integer (3));
    _methods.put ("setDuration", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // idl/Library/createAccount
       {
         String firstName = in.read_string ();
         String lastName = in.read_string ();
         String emailAddress = in.read_string ();
         String phoneNumber = in.read_string ();
         String username = in.read_string ();
         String password = in.read_string ();
         String educationalInstitution = in.read_string ();
         String $result = null;
         $result = this.createAccount (firstName, lastName, emailAddress, phoneNumber, username, password, educationalInstitution);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // idl/Library/reserveBook
       {
         String username = in.read_string ();
         String password = in.read_string ();
         String bookName = in.read_string ();
         String authorName = in.read_string ();
         String $result = null;
         $result = this.reserveBook (username, password, bookName, authorName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // idl/Library/reserveInterLibrary
       {
         String username = in.read_string ();
         String password = in.read_string ();
         String bookName = in.read_string ();
         String authorName = in.read_string ();
         String $result = null;
         $result = this.reserveInterLibrary (username, password, bookName, authorName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // idl/Library/getNonRetuners
       {
         String adminUsername = in.read_string ();
         String adminPassword = in.read_string ();
         String educationalInstitution = in.read_string ();
         int numDays = in.read_long ();
         String $result = null;
         $result = this.getNonRetuners (adminUsername, adminPassword, educationalInstitution, numDays);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // idl/Library/setDuration
       {
         String username = in.read_string ();
         String bookName = in.read_string ();
         int num_of_days = in.read_long ();
         String $result = null;
         $result = this.setDuration (username, bookName, num_of_days);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:idl/Library:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Library _this() 
  {
    return LibraryHelper.narrow(
    super._this_object());
  }

  public Library _this(org.omg.CORBA.ORB orb) 
  {
    return LibraryHelper.narrow(
    super._this_object(orb));
  }


} // class LibraryPOA
