package idl;

/**
* idl/ReplicaManagerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/ReplicaManager.idl
* Wednesday, November 26, 2014 10:37:55 PM EST
*/

public final class ReplicaManagerHolder implements org.omg.CORBA.portable.Streamable
{
  public idl.ReplicaManager value = null;

  public ReplicaManagerHolder ()
  {
  }

  public ReplicaManagerHolder (idl.ReplicaManager initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = idl.ReplicaManagerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    idl.ReplicaManagerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return idl.ReplicaManagerHelper.type ();
  }

}
