package idl;


/**
* idl/ReplicaManagerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/ReplicaManager.idl
* Wednesday, November 26, 2014 10:37:55 PM EST
*/

public interface ReplicaManagerOperations 
{
  void handleFailure (String educationalInstitution, String rmId);
  void sendHeartBeats ();
  String processHeartBeat (String educationalInstitution);
  boolean getCrashAgreement (int crashedRMId, int notifierRMId);
} // interface ReplicaManagerOperations
