module DRMSIDL 
{
	interface DRMS
	{
	long createAccount(in string _first_name,in string _last_name,in string _email,in string _username,in string _password,in string _institute,in long _phone_no) ;
	boolean studentLogin(in string _username,in string _password);
	boolean reserveBook(in string _usrename,in string _book_name);
	boolean addBook(in string _bookName,in string _authorName);
	string getNonReturners(in long duration);
	boolean setDuration(in string student,in long _noOfDays);
	boolean reserveInterLibrary(in string _username,in string _password, in string _bookName,in string _authorName);

	
	};
	
};
