module DRMSServices {
struct lateStudent {
		string firstName ;
		string lastName ;
		string phoneNumber ;
} ;

struct nonReturners {
	string universityName ;
	sequence<lateStudent> studentList ;
} ;
interface LibraryInterface {
	boolean createAccount ( in string firstName, in string lastName, in string email, in string phoneNumber, in string username, in string password, in string educationalInstitute ) ;
	
	boolean reserveBook ( in string username, in string password, in string bookName, in string authorName ) ;

	boolean reserveInterLibrary ( in string username, in string password, in string bookName, in string authorName ) ;

	typedef sequence<nonReturners> result ;
	result getNonReturners ( in string username, in string password, in string educationalInstitute, in long days ) ;

	boolean setDuration ( in string username, in string password, in string studentUsername, in string bookName, in string authorName, in long days ) ;
 
} ;
};
