package DRMSServices;


/**
* DRMSServices/lateStudent.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/LibraryInterface.idl
* Saturday, November 29, 2014 10:32:14 PM EST
*/

public final class lateStudent implements org.omg.CORBA.portable.IDLEntity
{
  public String firstName = null;
  public String lastName = null;
  public String phoneNumber = null;

  public lateStudent ()
  {
  } // ctor

  public lateStudent (String _firstName, String _lastName, String _phoneNumber)
  {
    firstName = _firstName;
    lastName = _lastName;
    phoneNumber = _phoneNumber;
  } // ctor

} // class lateStudent
