package DRMSServices;

/**
* DRMSServices/LibraryInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/LibraryInterface.idl
* Sunday, November 30, 2014 5:55:36 PM EST
*/

public final class LibraryInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public DRMSServices.LibraryInterface value = null;

  public LibraryInterfaceHolder ()
  {
  }

  public LibraryInterfaceHolder (DRMSServices.LibraryInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DRMSServices.LibraryInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DRMSServices.LibraryInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DRMSServices.LibraryInterfaceHelper.type ();
  }

}
