package DRMSServices;


/**
* DRMSServices/LibraryInterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/LibraryInterface.idl
* Sunday, November 30, 2014 5:55:36 PM EST
*/

abstract public class LibraryInterfaceHelper
{
  private static String  _id = "IDL:DRMSServices/LibraryInterface:1.0";

  public static void insert (org.omg.CORBA.Any a, DRMSServices.LibraryInterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static DRMSServices.LibraryInterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (DRMSServices.LibraryInterfaceHelper.id (), "LibraryInterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static DRMSServices.LibraryInterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_LibraryInterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, DRMSServices.LibraryInterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static DRMSServices.LibraryInterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof DRMSServices.LibraryInterface)
      return (DRMSServices.LibraryInterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      DRMSServices._LibraryInterfaceStub stub = new DRMSServices._LibraryInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static DRMSServices.LibraryInterface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof DRMSServices.LibraryInterface)
      return (DRMSServices.LibraryInterface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      DRMSServices._LibraryInterfaceStub stub = new DRMSServices._LibraryInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
