package DRMSServices;


/**
* DRMSServices/nonReturnersHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/LibraryInterface.idl
* Saturday, November 29, 2014 10:32:14 PM EST
*/

abstract public class nonReturnersHelper
{
  private static String  _id = "IDL:DRMSServices/nonReturners:1.0";

  public static void insert (org.omg.CORBA.Any a, DRMSServices.nonReturners that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static DRMSServices.nonReturners extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "universityName",
            _tcOf_members0,
            null);
          _tcOf_members0 = DRMSServices.lateStudentHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "studentList",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (DRMSServices.nonReturnersHelper.id (), "nonReturners", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static DRMSServices.nonReturners read (org.omg.CORBA.portable.InputStream istream)
  {
    DRMSServices.nonReturners value = new DRMSServices.nonReturners ();
    value.universityName = istream.read_string ();
    int _len0 = istream.read_long ();
    value.studentList = new DRMSServices.lateStudent[_len0];
    for (int _o1 = 0;_o1 < value.studentList.length; ++_o1)
      value.studentList[_o1] = DRMSServices.lateStudentHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, DRMSServices.nonReturners value)
  {
    ostream.write_string (value.universityName);
    ostream.write_long (value.studentList.length);
    for (int _i0 = 0;_i0 < value.studentList.length; ++_i0)
      DRMSServices.lateStudentHelper.write (ostream, value.studentList[_i0]);
  }

}
