package DRMSServices.LibraryInterfacePackage;


/**
* DRMSServices/LibraryInterfacePackage/resultHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/LibraryInterface.idl
* Sunday, November 30, 2014 5:55:36 PM EST
*/

abstract public class resultHelper
{
  private static String  _id = "IDL:DRMSServices/LibraryInterface/result:1.0";

  public static void insert (org.omg.CORBA.Any a, DRMSServices.nonReturners[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static DRMSServices.nonReturners[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = DRMSServices.nonReturnersHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (DRMSServices.LibraryInterfacePackage.resultHelper.id (), "result", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static DRMSServices.nonReturners[] read (org.omg.CORBA.portable.InputStream istream)
  {
    DRMSServices.nonReturners value[] = null;
    int _len0 = istream.read_long ();
    value = new DRMSServices.nonReturners[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = DRMSServices.nonReturnersHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, DRMSServices.nonReturners[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      DRMSServices.nonReturnersHelper.write (ostream, value[_i0]);
  }

}
