/**
 * IDL interface.
 * To generate files, go to "src" folder and run command "idlj -fall idl/LibraryServer.idl".
 */
module idl
{
	interface Library
	{
		string createAccount(in string firstName, in string lastName, in string emailAddress, in string phoneNumber, in string username,
			in string password, in string educationalInstitution);
			
		string reserveBook(in string username, in string password, in string bookName, in string authorName);
		
		string reserveInterLibrary(in string username, in string password, in string bookName, in string authorName);
		
		string getNonRetuners(in string adminUsername, in string adminPassword, in string educationalInstitution, in long numDays);
		
		string setDuration(in string username, in string bookName, in long num_of_days);
	};
};