package idl;

/**
* idl/LibraryHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/LibraryServer.idl
* Thursday, October 23, 2014 12:19:51 AM EDT
*/

public final class LibraryHolder implements org.omg.CORBA.portable.Streamable
{
  public idl.Library value = null;

  public LibraryHolder ()
  {
  }

  public LibraryHolder (idl.Library initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = idl.LibraryHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    idl.LibraryHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return idl.LibraryHelper.type ();
  }

}
