package idl;


/**
* idl/Library.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/LibraryServer.idl
* Thursday, October 23, 2014 12:19:51 AM EDT
*/

public interface Library extends LibraryOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Library
